### ISSUE TITLE
Probleme mit der ersten LED

### ISSUE THREAD

**Issue by MikeTsenatek** [manfred-hofmann/Wortuhr_ESP8266#11]
Hallo,

ich hab leider probleme mit der ersten LED. Diese ist bei mir eine Minuten LED. (Aus Historischen Gründen, ich hab früher eine andere Firmware drauf)

`#ifdef LED_LAYOUT_HORIZONTAL_4
uint8_t ledMap[] = {
  4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
  25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
  26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
  47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37,
  48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
  69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59,
  70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
  91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81,
  92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102,
  113, 112, 111, 110, 109, 108, 107, 106, 105, 104, 103,
  2, 1, 0, 3
};
#endif`

Leider geht die erste LED nur sehr sporatisch (v.a. nach der Änderung der Helligkeit in den Settings).

Hardware Defekt kann ich ausschließen, ich hab zum Testen eine andere Software (erst selbstgeschrieben, danach WLED) installiert, bei beiden funktioniert die LED einwandfrei.

Die LED 2,1, und 3 gehen einwandfrei.

Gibt es irgendeine Idee, wo ich suchen könnte.

VG
Philipp

**Comment by manfred-hofmann** [comment]
Hallo Philipp, 
Du kannst mal versuchen den Eintrag 0 mit z. B. 1,2 oder 3 zu tauschen und schauen ob der Fehler mitwandert. 

Hast du die Versionen alle geprüfte? 
Besonders die neuestes Version von Adafruit NeoPixel (Version 1.10.6) installiert? 

WLED benutzt die FastLED Library!
Gruß
Manfred

**Comment by MikeTsenatek** [comment]
Hallo Manfred,

ich benutzte die 1.10.7 von NeoPixel. 
Wenn ich die 2,1,0,3 ändere, es bleibt immer die gleiche LED (die 0er) aus.

VG
Philipp

**Comment by manfred-hofmann** [comment]
Hallo Philipp,
Du kannst mal die Matrix Tests oder den Animationseditor starten. Da sind die Minuten LEDs dauerhaft an.
Wenn es immer die erste LED ist, kann es auch daran liegen, das der Pegel  nicht ganz ausreicht. Der sollte mind. 70% der Versorgungsspannung sein. Das sind bei 5V 3,5V. Da kannst du mal versuchen die erste LED mit einer Diode zwischen der Stromzuführung zu versorgen. Dann ist die Versorgungsspannung der erste LED 4,5V. Also 3,15V für high Pegel. Ich hatte auch schonmal eine LED mit thermischen Problem. Da gingen aber auch alle nachfolgenden LEDs nicht mehr. 
Kannst du mal die LED mal tauschen, oder diese auslassen und mit der Einspeisung bei der zweiten beginnen?

Gruß 
Manfred

**Comment by MikeTsenatek** [comment]
Hallo Manfred,

hab jetzt folgendes probiert:
1) kleiner Sketch mit allen LEDs an in random Farbe mit Neopixel => LED geht
2) LED getauscht 
3) Pegelwandler eingesetzt (Mosfet, zwei Widerstände)
4) Wemos getauscht
5) Matrix Test => LED geht
6) Tetris => LED geht

Die LED geht überall, nur nicht mit dem Wordclock Sketch. Langsam bin ich echt überfragt.

Was mir noch eingefallen ist, anfangs hatte ich die ESP32 Version drauf (hatte diese hier erst später entdeckt), hier lief die LED auch.

VG
Philipp

**Comment by MikeTsenatek** [comment]
Glaub ich hab den Fehler....

meine ledmap war keine Konstante... 

Sry für die Beschäftigung

**Comment by MikeTsenatek** [comment]
Hmm, jetzt hab ich einen anderen Bug.

Jetzt geht im Uhrenmodus die 12. LED nicht (das Ü in der 1. Zeile).

Beim Matrixtest funktioniert sie, aber beim Anzeigen der 5. Zeile leuchtet zusätzlich mit.

**Comment by MikeTsenatek** [comment]
Glaub auch da war ich Schuld..., es fehlte eine 115. LED in der LEDMap, auch wenn ich keine Angeschlossen hab. 

Gibt es irgendwo ein https://www.buymeacoffee.com/ Link o.ä.?

Ich schließe es hier
