### ISSUE TITLE
WLAN Probleme

### ISSUE THREAD

**Issue by xpilzx1** [manfred-hofmann/Wortuhr_ESP8266#12]
Hallo zusammen,
Hallo Manfred,
Zuerst einmal Danke für die viele Arbeit die in diesem Projekt steckt, und dafür das es und frei zur Verfügung gestellt wird. 
Ich habe da ein Problem mit der WLAN Verbindung. Ich habe die Audiofunktion sowie die IR Fernbedinung auskommentiert. Die Uhr läuft etwa 10 bis 20h wie sie soll, und dann irgendwann geht die Verbindung verloren.
Über die Website ist Sie auch nicht zu erreichen, aber es wird wieder ein WLAN zur Verfügung gestellt.
In dem Netz können aber nicht die wlandaten eingegeben werden, sondern es wird die Website unter der standart IP aufgerufen.
Da die Inet Verbindung fehlt bleibt die Uhrzeit stehen und die Wetter API ohne Inhalt.
Ich weiss leider nicht weiter. Jemand eine Idee??

**Comment by manfred-hofmann** [comment]
Was passiert, wenn du den ESP neu startest?

**Comment by xpilzx1** [comment]
Rebot und aus / ein bringen keine Änderung. Die Website ist nur unter der Standard IP zu erreichen. Ein wifireset ermöglicht es wieder die Routerdaten einzugeben und dann läuft das ganze wieder für ein paar Stunden.

**Comment by manfred-hofmann** [comment]
Wenn ich das richtig verstehe, macht der ESP immer nur einen AP auf. D.h. beim Neustart wird das WiFi Symbol nicht grün! Schaltest du dein WLAN z.B. nachts aus?  
Kannst Du mal Versuchen alles neu mit der Board Version 3.0.2 zu laden.

**Comment by xpilzx1** [comment]
Ja so ist es ä. Er macht immer einen AP auf und vergisst die IP. Mein WLAN läuft durch, und ich habe das ganze schon mit V3.0.2 geladen.
Ich nutze ein D1 Pro .
Ich habe mir auch überlegt den AP einfach abzuschalten, und SSID sowie PW meines Netzes einfach Fix zu hinterlegen.
Leider reichen meine Arduinomoves nicht aus. Ich konnte die Stelle mit der WIFI Verbindung nicht im Code finden.

**Comment by manfred-hofmann** [comment]
Das ist alles sehr merkwürdig. Evtl. hat dein ESP ein Problem. Normalerweise werden SSID und PW dauerhaft im Flash gespeichert und nur durch wifireset gelöscht. Die Stelle, wo die WiFi Verbindung gestartet wird findest du im Code wenn du nach  "WiFiManager wifiManager;" suchst.

**Comment by xpilzx1** [comment]
Ich denke ich habe die Lösung gefunden. So wie es ausschaut waren Sonderzeichen in der SSID das Problem. Nachdem ich die Uhr Testweise mit meinem Gastnetz verbunden hatte lief Sie tadellos.
Noch ist zwar nicht viel Zeit vergangen, aber Sie läuft jetzt schon über 40h am Stück.  Und auch das wiederverbinden nach einem netzwerkausfall geht deutlich schneller und problemloser .
Vielen Dank nochmal
