### ISSUE TITLE
Compilierungsfehler variable or field 'setMode' declared void

### ISSUE THREAD

**Issue by WRT0815** [manfred-hofmann/Wortuhr_ESP8266#13]
Hallo,
ich bin totaler Anfänger in der Programmierung, fand das Projekt aber super spannend zum nachbauen.

Leider scheitere ich jetzt bereits beim compilieren der SW in Arduino IDE.

Ich bekomme  Compilierungsfehler immer wo "setMode()" aufgerufen wird.
Hier die Stelle an der das zum ersten Mal auftritt:
...
... Arduino\Wortuhr_esp\Wortuhr_mp3.ino:1081:7: error: 'setMode' was not declared in this scope; did you mean 'eMode'?
 1081 |       setMode(MODE_BLANK);
      |       ^~~~~~~
      |       eMode
...
Compilation error: variable or field 'setMode' declared void...

Kann mir hierzu vielleicht jemand einen Tipp geben? Gut möglich dass das Problem vor dem Computer sitzt in meinem Fall.
Was könnte denn das Problem sein.

Ich nutze Arduino IDE 2.0.4 hatte auch schon was gelesen, dass es special effexcts geben kann beim Compilieren je nach Version.

Ich habe am Code nichts geändert. 
Lediglich im Config File die APIKEY für das Wetter auskommentiert. (ist aber irrelevant für das Problem)

Gruß Tobias

**Comment by manfred-hofmann** [comment]
Evtl. liegt es an der Arduino IDE. Ich verwende immer noch die 1.8.X Version. Die scheint ein wenig genügsamer zu sein.

**Comment by WRT0815** [comment]
Hallo danke für die schnelle Rückmeldung. Ich hab das nochmal in Ruhe alles neu gemacht zunächst mit der IDE 1.8.x danach mit der aktuellen 2.0.4 und jetzt konnte ich compilieren und uploaden (auch mit 2.0.4). Also das Problem war wohl ich selbst. Glaube ich hatte im Sketch noch versehentlich eine alte Datei mit drin. 
Jetzt wo der ESP läuft werde ich die Hardware aufbauen. Nochmal lieben Dank. Super Projekt.
