### ISSUE TITLE
Themes für das Frontend?

### ISSUE THREAD

**Issue by c64emulator** [manfred-hofmann/Wortuhr_ESP8266#15]
Die jetzige Gestaltung des Frontends ist nicht jedermans Geschmack. Da wären Themes ganz cool. Vor allem sollten solche Einstellungen auch nach einem Update erhalten bleiben und ggf. auch ein Backup möglich sein.
Ein Dark Theme wäre z.B. ganz gut, würde sich besonders gut auf einem Handy mit AMOLED-Display (die haben aus Energiespar-Gründen oft ein Dark Theme eingestellt) machen.

**Comment by manfred-hofmann** [comment]
Mir gefällt das Frontend. Jedoch kann jeder die css Files nach belieben ändern. Es ist ja auch nicht so, dass man das Frontend täglich benötigt um mit einem Dark Modus Energie zu sparen. Zumal die Uhr selbst ja nicht gerade Energiesparend ist.
