### ISSUE TITLE
Bin FIle in Repo

### ISSUE THREAD

**Issue by n3roGit** [manfred-hofmann/Wortuhr_ESP8266#2]
Es wäre toll, wenn du ein .bin File immer im Git bereitstellen könntest.

Ich bin ziemlich am verzweifeln, das Projekt zu kompilieren :D ....

`sketch\Events.cpp: In function 'bool loadEvents()':
Events.cpp:57:56: error: ambiguous overload for 'operator=' (operand types are 'String' and 'JSONVar')
   57 |         events[z].text = myObject["events"][z-1]["text"];
      |                                                        ^
In file included from C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/Arduino.h:286,
                 from sketch\Events.h:6,
                 from sketch\Events.cpp:1:
C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/WString.h:101:17: note: candidate: 'String& String::operator=(const char*)'
  101 |         String &operator =(const char *cstr);
      |                 ^~~~~~~~
C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/WString.h:104:17: note: candidate: 'String& String::operator=(char)'
  104 |         String &operator =(char c) {
      |                 ^~~~~~~~
Events.cpp:61:58: error: ambiguous overload for 'operator=' (operand types are 'String' and 'JSONVar')
   61 |         events[z].preani=myObject["events"][z-1]["preani"];
      |                                                          ^
In file included from C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/Arduino.h:286,
                 from sketch\Events.h:6,
                 from sketch\Events.cpp:1:
C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/WString.h:101:17: note: candidate: 'String& String::operator=(const char*)'
  101 |         String &operator =(const char *cstr);
      |                 ^~~~~~~~
C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/WString.h:104:17: note: candidate: 'String& String::operator=(char)'
  104 |         String &operator =(char c) {
      |                 ^~~~~~~~
Events.cpp:63:60: error: ambiguous overload for 'operator=' (operand types are 'String' and 'JSONVar')
   63 |         events[z].postani=myObject["events"][z-1]["postani"];
      |                                                            ^
In file included from C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/Arduino.h:286,
                 from sketch\Events.h:6,
                 from sketch\Events.cpp:1:
C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/WString.h:101:17: note: candidate: 'String& String::operator=(const char*)'
  101 |         String &operator =(const char *cstr);
      |                 ^~~~~~~~
C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/WString.h:104:17: note: candidate: 'String& String::operator=(char)'
  104 |         String &operator =(char c) {
      |                 ^~~~~~~~
sketch\OpenWeather.cpp: In member function 'uint16_t OpenWeather::getOutdoorConditions(String, String)':
OpenWeather.cpp:61:66: error: ambiguous overload for 'operator=' (operand types are 'String' and 'JSONVar')
   61 |           sdescription = weatherArray["weather"][z]["description"];
      |                                                                  ^
In file included from C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/Arduino.h:286,
                 from C:\Users\Username\SynologyDrive\WindowsProfile\Documents\arduino\libraries\Arduino_JSON\src/JSON.h:23,
                 from C:\Users\Username\SynologyDrive\WindowsProfile\Documents\arduino\libraries\Arduino_JSON\src/Arduino_JSON.h:23,
                 from sketch\OpenWeather.h:8,
                 from sketch\OpenWeather.cpp:5:
C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/WString.h:101:17: note: candidate: 'String& String::operator=(const char*)'
  101 |         String &operator =(const char *cstr);
      |                 ^~~~~~~~
C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/WString.h:104:17: note: candidate: 'String& String::operator=(char)'
  104 |         String &operator =(char c) {
      |                 ^~~~~~~~
OpenWeather.cpp:66:61: error: ambiguous overload for 'operator=' (operand types are 'String' and 'JSONVar')
   66 |             weathericon1 = weatherArray["weather"][z]["icon"];
      |                                                             ^
In file included from C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/Arduino.h:286,
                 from C:\Users\Username\SynologyDrive\WindowsProfile\Documents\arduino\libraries\Arduino_JSON\src/JSON.h:23,
                 from C:\Users\Username\SynologyDrive\WindowsProfile\Documents\arduino\libraries\Arduino_JSON\src/Arduino_JSON.h:23,
                 from sketch\OpenWeather.h:8,
                 from sketch\OpenWeather.cpp:5:
C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/WString.h:101:17: note: candidate: 'String& String::operator=(const char*)'
  101 |         String &operator =(const char *cstr);
      |                 ^~~~~~~~
C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/WString.h:104:17: note: candidate: 'String& String::operator=(char)'
  104 |         String &operator =(char c) {
      |                 ^~~~~~~~
OpenWeather.cpp:71:61: error: ambiguous overload for 'operator=' (operand types are 'String' and 'JSONVar')
   71 |             weathericon2 = weatherArray["weather"][z]["icon"];
      |                                                             ^
In file included from C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/Arduino.h:286,
                 from C:\Users\Username\SynologyDrive\WindowsProfile\Documents\arduino\libraries\Arduino_JSON\src/JSON.h:23,
                 from C:\Users\Username\SynologyDrive\WindowsProfile\Documents\arduino\libraries\Arduino_JSON\src/Arduino_JSON.h:23,
                 from sketch\OpenWeather.h:8,
                 from sketch\OpenWeather.cpp:5:
C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/WString.h:101:17: note: candidate: 'String& String::operator=(const char*)'
  101 |         String &operator =(const char *cstr);
      |                 ^~~~~~~~
C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/WString.h:104:17: note: candidate: 'String& String::operator=(char)'
  104 |         String &operator =(char c) {
      |                 ^~~~~~~~
sketch\Animation.cpp: In function 'bool loadAnimation(String)':
Animation.cpp:139:44: error: ambiguous overload for 'operator=' (operand types are 'String' and 'JSONVar')
  139 |           wert = myObject["Palette"][palidx];
      |                                            ^
In file included from C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/Arduino.h:286,
                 from sketch\Animation.h:7,
                 from sketch\Animation.cpp:1:
C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/WString.h:101:17: note: candidate: 'String& String::operator=(const char*)'
  101 |         String &operator =(const char *cstr);
      |                 ^~~~~~~~
C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/WString.h:104:17: note: candidate: 'String& String::operator=(char)'
  104 |         String &operator =(char c) {
      |                 ^~~~~~~~
sketch\Animation.cpp: In function 'bool loadFrames(uint8_t, String)':
Animation.cpp:196:40: error: ambiguous overload for 'operator=' (operand types are 'String' and 'JSONVar')
  196 |       farbwert = myObject[zeile_json][x];
      |                                        ^
In file included from C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/Arduino.h:286,
                 from sketch\Animation.h:7,
                 from sketch\Animation.cpp:1:
C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/WString.h:101:17: note: candidate: 'String& String::operator=(const char*)'
  101 |         String &operator =(const char *cstr);
      |                 ^~~~~~~~
C:\Users\Username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/WString.h:104:17: note: candidate: 'String& String::operator=(char)'
  104 |         String &operator =(char c) {
      |                 ^~~~~~~~
exit status 1
ambiguous overload for 'operator=' (operand types are 'String' and 'JSONVar')
`

**Comment by manfred-hofmann** [comment]
Versuche es mal mit der ESP8266 Boardversion 2.6.3

**Comment by n3roGit** [comment]
Werde ich morgen testen :)

**Comment by manfred-hofmann** [comment]
Hat es geklappt?

**Comment by manfred-hofmann** [comment]
Ich mach mal zu.
