### ISSUE TITLE
Keine Daten vom BME_280

### ISSUE THREAD

**Issue by Phi2ipp** [manfred-hofmann/Wortuhr_ESP8266#5]
Hallo,

ich verwende den 6 Pin (VCC, GND, SCL, SDA, CSB, SDO) BME 280 Sensor.
Diesen habe ich wie im Schaltplan angeschlossen, aber leider spuckt er keine Daten aus.
Auf der Info-Seite des ESP8266 werden es immer mehr "Error (BME): 60"

Kannst du mir hier weiterhelfen?

**Comment by manfred-hofmann** [comment]
Ich glaube du musst hier noch zusätzlich den CSB Pin auf VCC (3,3V) legen.

**Comment by Phi2ipp** [comment]
Das bringt leider keine Veränderung.
Wird wohl der Sensor defekt sein.

**Comment by manfred-hofmann** [comment]
Evtl. stimmt die Adresse auch nicht. Schau mal ins Datenblatt. Mit SD0 wird zwischen 0x76 und 0x77 umgeschaltet. Ich glaub für die default Adresse des BME280 muss der SD0 auf Masse liegen. Oder mach mal mit einem Scan Programm einen I2c scan, ob dein BME280 gefunden wird.

**Comment by Phi2ipp** [comment]
Der BME280 wird nicht im I2C gefunden. Ich vermuter er ist defekt. 
Werde mir einen neuen besorgen und es noch mal testen.

**Comment by manfred-hofmann** [comment]
👍
