### ISSUE TITLE
16x16 LED Matrix support?

### ISSUE THREAD

**Issue by bmk666** [manfred-hofmann/Wortuhr_ESP8266#7]
Hi Manfred,

erst mal vielen dank für das tolle Projekt!

Wäre es Möglich eine fertige 16x16 LED Matrix zu verwenden?

z.B. [Link](https://www.amazon.de/HER-WS2812B-Flexible-Individually-addressable/dp/B08DVBGRRL/ref=sr_1_10?keywords=led+matrix+16x16&qid=1646037661&sprefix=led+matrix+16%2Caps%2C81&sr=8-10)

Das würde das Bauen einer solchen Uhr extrem vereinfachen!

Und man könnte vielleicht die zusätzlichen Pixel für Sekunden nehmen wie z.B. bei dem Projekt:
[Link](https://www.thingiverse.com/thing:5073594)

Danke und viele Grüße,

Sascha

**Comment by manfred-hofmann** [comment]
Hallo Sascha,
möglich ist viel.
Jedoch ist die 16x16 Matrix schon sehr klein.
Du musst einfach die LED Matrix in LedDriver.cpp entsprechend anpassen. Ist unten in der Readme auf der Hauptseite erklärt. 
Ein "Sekundenzeiger" ist aktuell nicht vorgesehen.
Gruß
Manfred

**Comment by bmk666** [comment]
Hi, 

Ja von wegen der Größe ist es mehr was für den Schreibtisch, nicht für die Wand!
Nochmals danke!

Grüße,
Sascha
