### ISSUE TITLE
RTC Modul

### ISSUE THREAD

**Issue by LeifGitHub** [manfred-hofmann/Wortuhr_ESP8266#8]
Ein wirklich unglaubliches Projekt. Hast du bereits über die Integration einer RealTimeClock nachgedacht, sodass man die Uhr nur zum aufsetzten mit WiFi betreiben muss?

**Comment by manfred-hofmann** [comment]
Ohne WiFi macht die Uhr keinen Sinn, da dann das Web frontend und open weather nicht mehr funktionieren. Außerdem sollte doch inzwischen jeder ein WLAN zu Hause haben.
Gruß

**Comment by LeifGitHub** [comment]
Vielen Dank für die schnelle Antwort. Ich hatte an ein Fallback falls das Internet ausfällt gedacht, auch würde das Modul und der Traffic weniger belastet? An manchen Orten gibt es zudem auch nur stark gesicherte Wifis oder es wird mit temporären HotSpots agiert. Wie könnte sowas denn integriert werden, wäre über Hinweise dankbar! Vermutlich doch eine, RTC Library hinterlegen, den Verweis auf die RTC und nicht den Zeitserver, nur beim booten/ Neustart gucken ob Internet vorhanden ist und wenn möglich die Zeit aktualisieren?

**Comment by manfred-hofmann** [comment]
Auch wenn das I-Net über mehrere Stunden ausfällt, hält der ESP die Uhrzeit sehr genau. Einen Ausfall des Internets über mehrere Tage hatte ich noch nicht. Ein RTC Modul ist trotzdem in der SW vorgesehen. Siehe Configuration.h Es gibt einige Leute, die betreiben die Uhr mit RTC MODUL (z. B. espuno siehe Wortuhrforum)
Gruß

**Comment by LeifGitHub** [comment]
Vielen Dank!
