### ISSUE TITLE
Problem mit Fronplatte ?

### ISSUE THREAD

**Issue by interceptor70** [manfred-hofmann/Wortuhr_ESP8266#9]
Erstmal ganz wichtig ein super Projekt 😊
Aber leider stehe ich auf dem schlauch wegen der frontplatte,
Die ich aus einem alten Project habe.

Wie bekomme ich das hin das die Buchstaben wieder passen ?
Erstmal ganz wichtig ein super Projekt 😊
Aber leider stehe ich auf dem schlauch wegen der frontplatte,
Die ich aus einem alten Project habe.

Wie bekomme ich das hin das die Buchstaben wieder passen ?

p.s. start led rechts unten

untersten symbole sind die minuten

lg Gerrit 
![de_DE_s1](https://user-images.githubusercontent.com/35465613/201547575-484cb8f9-4265-4cad-9dfc-9ab0230e889b.svg)

**Comment by manfred-hofmann** [comment]
Hallo Gerrit,
schau mal hier auf der Startseite unten ist erklärt wir das mit dem Layout funktioniert.
Gruß
Manfred

**Comment by interceptor70** [comment]
Das ist ja mein Problem das kann ich ja ändern.
Die Reihenfolge ändern ist ja nicht das problem…. Lach 

Die worte passen nicht zusammen weil ich eine 11 x 11 Matrix habe.

Vom panbachi aber leider ist die nicht so schön bunt wie deine version 😊



> int Grid_de_DE_s1::time_it_is[5] = {0, 1, 3, 4, 5}; // es ist
> 
> int Grid_de_DE_s1::time_minutes[12][12] = {
>   {107, 108, 109,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1}, // uhr
>   {  7,   8,   9,  10,  35,  36,  37,  38,  -1,  -1,  -1,  -1}, // fünf nach
>   { 11,  12,  13,  14,  35,  36,  37,  38,  -1,  -1,  -1,  -1}, // zehn nach
>   { 26,  27,  28,  29,  30,  31,  32,  35,  36,  37,  38,  -1}, // viertel nach
>   { 15,  16,  17,  18,  19,  20,  21,  35,  36,  37,  38,  -1}, // zwanzig nach
>   {  7,   8,   9,  10,  39,  40,  41,  44,  45,  46,  47,  -1}, // fünf vor halb
>   { 44,  45,  46,  47,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1}, // halb
>   {  7,   8,   9,  10,  35,  36,  37,  38,  44,  45,  46,  47}, // fünf nach halb
>   { 15,  16,  17,  18,  19,  20,  21,  39,  40,  41,  -1,  -1}, // zwanzig vor
>   { 26,  27,  28,  29,  30,  31,  32,  39,  40,  41,  -1,  -1}, // viertel vor
>   { 11,  12,  13,  14,  39,  40,  41,  -1,  -1,  -1,  -1,  -1}, // zehn vor
>   {  7,   8,   9,  10,  39,  40,  41,  -1,  -1,  -1,  -1,  -1}  // fünf vor
> };
> 
> int Grid_de_DE_s1::time_hours[12][6] = {
>   { 49,  50,  51,  52,  53,  -1}, // zwölf
>   { 57,  58,  59,  60,  -1,  -1}, // eins
>   { 55,  56,  57,  58,  -1,  -1}, // zwei
>   { 67,  68,  69,  70,  -1,  -1}, // drei
>   { 84,  85,  86,  87,  -1,  -1}, // vier
>   { 73,  74,  75,  76,  -1,  -1}, // fünf
>   {100, 101, 102, 103, 104,  -1}, // sechs
>   { 60,  61,  62,  63,  64,  65}, // sieben
>   { 89,  90,  91,  92,  -1,  -1}, // acht
>   { 80,  81,  82,  83,  -1,  -1}, // neun
>   { 93,  94,  95,  96,  -1,  -1}, // zehn
>   { 77,  78,  79,  -1,  -1,  -1}  // elf
> };
>

**Comment by interceptor70** [comment]
Dann schaut das ja so aus, 
wenn ich das richtig verstehe oder ?

aber die Wörter passen dann nicht wie kann ich die verschieben oder wo ?


> #ifdef LED_LAYOUT_VERTICAL_3
    uint8_t ledMap[] = {
        120, 119, 118, 117, 116, 115, 114, 113, 112, 111, 110,
        109, 108, 107, 106, 105, 104, 103, 102, 101, 100,  99,
         98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
         87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,
         76,  75,  74,  73,  72,  71,  70,  69,  68,  67,  66,
         65,  64,  63,  62,  61,  60,  59,  58,  57,  56,  55,
         54,  53,  52,  51,  50,  49,  48,  47,  46,  45,  44,
         43,  42,  41,  40,  39,  38,  37,  36,  35,  34,  33,
         32,  31,  30,  29,  28,  27,  26,  25,  24,  23,  22,
         21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,
         2,  4,  5,  6,  8
    };
#endif

**Comment by manfred-hofmann** [comment]
Du hast 2 Probleme
1. Du hast 121 Leds
2. Deine Worte passen nicht. 
zu 1
Du kannst versuchen in configuration.h die NUMPIXELS auf 121 zu setzen. Dann solltest du deine LEDs Layout anpassen können.
zu 2
Die Wörter werden in Words.h definiert.
Hier musst du halt jedes Wort an dein Layout anpassen.

**Comment by manfred-hofmann** [comment]
OK, hört sich gut an. 
Es wird bald ein neues Release rauskommen. Ich habe alles auf LittleFS umgestellt. Spiffs ist ja deprecated.
Und noch ein paar andere Änderungen.

**Comment by interceptor70** [comment]
Jup das cool 

Also erstmal die 11 x 11 
Panabacht ... matrix siehe oben (einspeisung unten rechts)

`#define DE_VOR				matrix[3] |= 0b0000001110000000
#define DE_NACH				matrix[3] |= 0b0011110000000000
#define DE_ESIST			matrix[0] |= 0b1101110000000000
#define DE_UHR				matrix[9] |= 0b0000000011100000
#define DE_AM				matrix[5] |= 0b0000011000000000
#define DE_PM				matrix[6] |= 0b0000110000000000

#define DE_FUENF			matrix[0] |= 0b0000000111100000
#define DE_ZEHN				matrix[1] |= 0b1111000000000000
#define DE_VIERTEL			matrix[2] |= 0b0000111111100000
#define DE_ZWANZIG			matrix[1] |= 0b0000111111100000
#define DE_HALB				matrix[4] |= 0b1111000000000000
#define DE_DREIVIERTEL		matrix[2] |= 0b1111111111100000

#define DE_H_EIN			matrix[5] |= 0b0011100000000000
#define DE_H_EINS			matrix[5] |= 0b0011110000000000
#define DE_H_ZWEI			matrix[5] |= 0b1111000000000000
#define DE_H_DREI			matrix[6] |= 0b0011110000000000
#define DE_H_VIER			matrix[7] |= 0b0000000111100000
#define DE_H_FUENF			matrix[6] |= 0b0000000111100000
#define DE_H_SECHS			matrix[9] |= 0b0111110000000000
#define DE_H_SIEBEN			matrix[5] |= 0b0000011111100000
#define DE_H_ACHT			matrix[8] |= 0b0111100000000000
#define DE_H_NEUN			matrix[7] |= 0b0001111000000000
#define DE_H_ZEHN			matrix[8] |= 0b0000011110000000
#define DE_H_ELF			matrix[7] |= 0b1110000000000000
#define DE_H_ZWOELF			matrix[4] |= 0b0000011111000000
`
und das LED_Layout

`    uint8_t ledMap[] = {
        120, 119, 118, 117, 116, 115, 114, 113, 112, 111, 110,
         99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
         98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
         76,  75,  74,  73,  72,  71,  70,  69,  68,  67,  66,
         55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         54,  53,  52,  51,  50,  49,  48,  47,  46,  45,  44,
         33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
         32,  31,  30,  29,  28,  27,  26,  25,  24,  23,  22,
         11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,
         8, 6, 4, 2,  0
    };`


GANZ WICHTIG :-) die anzahl der LED´s nicht vergessen 
 configuration.h die NUMPIXELS auf 121

lg Gerrit

**Comment by interceptor70** [comment]
> OK, hört sich gut an. Es wird bald ein neues Release rauskommen. Ich habe alles auf LittleFS umgestellt. Spiffs ist ja deprecated. Und noch ein paar andere Änderungen.

hoffentlich was mit Sound das bekomme ich jetzt nicht ans drehen.

> error: no matching function for call to 'SoftwareSerial::SoftwareSerial(const uint8_t&, const uint8_t&, bool, int)'

**Comment by manfred-hofmann** [comment]
Mach mal bei
`SoftwareSerial SoftSer(PIN_AUDIO_TX, PIN_AUDIO_RX, false, 128); `
Die 128 weg. 
Also nur
`SoftwareSerial SoftSer(PIN_AUDIO_TX, PIN_AUDIO_RX, false);`

**Comment by interceptor70** [comment]
Hmm ,
irgendwo was vergessen glaube ich... 

> Wortuhr_mp3:136:28: error: 'AUDIO_BASENR0' was not declared in this scope
>   136 | int16_t SOUNDBASENR[17] = {AUDIO_BASENR0,AUDIO_BASENR1,AUDIO_BASENR2,AUDIO_BASENR3,AUDIO_BASENR4,AUDIO_BASENR5,
>

**Comment by interceptor70** [comment]
Ich bastel gerade ein Layout, zum selber Ätzen, die Real Time Clock hattest du ja auch vorgesehen 
am gleichen I2C Bus oder Separat ?

LG Gerrit

**Comment by manfred-hofmann** [comment]
RTC brauchst du nicht. Der ESP ist genau genug, wenn jede Stunde die Zeit vom NTP Server geholt wird.
